FROM python:3.8

WORKDIR /app

COPY download.sh /usr/bin/download.sh
RUN git clone https://github.com/rpo19/AIQuestionAnswering.git backend

WORKDIR /app/backend

RUN pip install -r demo/backend/requirements.txt && \
    pip install -r knowledgeGraph/kgqalib/requirements.txt && \
    pip install -r text/ftqalib/requirements.txt && \
    mkdir -p data/models && \
    wget "https://raw.githubusercontent.com/circulosmeos/gdown.pl/master/gdown.pl" -O /usr/bin/gdown.pl && \
    chmod +x /usr/bin/gdown.pl && \
    chmod +x /usr/bin/download.sh

ENV PRODUCTION=true

ENTRYPOINT ["download.sh"]
CMD ["python", "demo/backend/server.py"]