FROM node:15 as builder
# manually copy :demo/frontend here
COPY frontend /frontend
RUN cd /frontend && npm install && npx ng build --configuration=production


FROM nginx:stable

COPY --from=builder /frontend/dist/frontend /usr/share/nginx/frontend
